### ISSUE TITLE
Add proper attribution for SheetJS

### ISSUE THREAD

**Issue by SheetJSDev** [bright-sea/webpivottable#1]
We are very glad that you found [js-xls](https://github.com/SheetJS/js-xls/blob/master/dist/xls.min.js) useful enough to include in [your library](https://github.com/bright-sea/webpivottable/blob/master/public/brightsea/dojo/dojo.js).  We would greatly appreciate it if you properly attributed the code (similar to the attribution for the zip library)

js-xls is [Apache 2](https://github.com/SheetJS/js-xls/blob/master/dist/LICENSE) licensed.  To be consistent, the comment should look like:

```
xls.js 2014 - SheetJS [ https://github.com/SheetJS/js-xls ] Apache 2.0 License
```

**Comment by bright-sea** [comment]
Hi SheetJSDev team,

We are using js-xls and js-xlsx lib to read xls and xlsx files in our
component WebPivotTable. They are quite useful and we appreciate your great
work.

Since we need wrap all our assets (include third party lib , like js-xls
and js-xlsx) into one minified file, we use dojo lib to declare js-xls and
js-xlsx as a local variable instead of global variable (no change of js-xls
and js-xlsx implementation)

Would you please advise us what we need to do in our case to follow your
license requirement?

For example, if we put list below statement

xls.js 2014 - SheetJS [ https://github.com/SheetJS/js-xls ] Apache 2.0
License

xlsx.js 2014 - SheetJS [ https://github.com/SheetJS/js-xlsx
https://github.com/SheetJS/js-xls ] Apache 2.0 License

into our README.MD
https://github.com/bright-sea/webpivottable/blob/master/README.md
and also attach one copy of your license file in our distribution zip
file, is that OK?

Thanks

Minghai Zhao

**Comment by SheetJSDev** [comment]
At the top of the source file, you already attribute zlib.js. Can you add the two lines there as well?

You should also include a license file in the project (to identify the license for the project). You don't have to use a free license if you have your own commercial one. In that license file you can identify the external dependencies and the relevant licenses.  For example, since js-xlsx source tree ships with JSZip, even though it is a separate source file, the main LICENSE file clarified the license terms: https://github.com/SheetJS/js-xlsx/blob/master/LICENSE#L15

Except where noted, this license applies to any and all software programs and associated documentation files created by the Original Author and distributed with the Software:

'jszip.js' is a modified version of JSZip, Copyright (c) Stuart Knightley, David Duponchel, Franz Buchinger, Ant'onio Afonso. JSZip is dual licensed and is used according to the terms of the MIT License.

If you would like to see more examples, the V8 and node.js projects have similar license structure.

**Comment by bright-sea** [comment]
Add dependences on els-js and xlsx-js on both source head and README.RM as well.

Thanks for this suggestion.
